import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-amber-600  p-4 text-black flex justify-around">next tutorial
          <Link href={'/'}>Home</Link>
          <Link href={'/products'}>Products</Link>
        </header>
        {children}
        <footer className="bg-amber-500 text-amber-50 text-center p-4">copyright @Divyanshu.2025</footer>
      </body>
    </html>
  );
}
